version: '3.8'

services:
  # Go Backend API (development with hot reload)
  backend:
    build: 
      context: ./backend
      target: development
    restart: always
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    volumes:
      - ./backend:/app
    depends_on:
      - db

  # SvelteKit Frontend (development mode)
  frontend:
    build:
      context: ./frontend
      target: development
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"  # Expose for development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Caddy Reverse Proxy & Web Server
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  caddy_data:
  caddy_config: