version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Go Backend API
  backend:
    build:
      context: ./backend
      target: production
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    ports:
      - "8080:8080"
    depends_on:
      - db

  # SvelteKit Frontend
  frontend:
    build:
      context: ./frontend
      target: production
    restart: always
    ports:
      - "5173:80"

  # Caddy Reverse Proxy
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  caddy_data:
  caddy_config: